from __future__ import annotations

import logging
from typing import Any, List, Optional, Tuple
import numpy as np
from arcengine import FrameData

from .actions import grid_to_pixel, pixel_to_grid
from .objects import GameObject, ObjectType
from .state import HUDState, PlayerState

logger = logging.getLogger()

COLORS = [12, 9, 14, 8]
ROTATIONS = [0, 90, 180, 270]


class PerceptionEngine:
    """Robust observation processing and feature extraction for ARC-AGI-3."""

    def __init__(self) -> None:
        self.last_detected_player: Optional[PlayerState] = None

    def reset_level(self) -> None:
        """Reset perception state for a clean level transition."""
        self.last_detected_player = None

    def extract_screen(
        self, frame_data: FrameData, use_latest: bool = True
    ) -> Optional[np.ndarray]:
        """
        Safely extract the 2D (64, 64) screen grid from FrameData.
        By default, selects the latest terminal frame generated by the action.
        """
        if frame_data is None:
            return None
        raw = getattr(frame_data, "frame", None)
        if raw is None:
            return None
        try:
            arr = np.asarray(raw)
            while arr.ndim > 2:
                # Use latest terminal subframe if multiple frames generated during action
                arr = arr[-1] if use_latest else arr[0]
            if arr.ndim == 2 and arr.shape == (64, 64):
                return arr.astype(np.int32)
        except Exception as e:
            logger.debug(f"[PERCEPTION] Failed to extract screen array: {e}")
        return None

    def extract_all_screens(self, frame_data: FrameData) -> List[np.ndarray]:
        """Extract all 2D screen states rendered during an action."""
        if frame_data is None:
            return []
        raw = getattr(frame_data, "frame", None)
        if raw is None:
            return []
        screens: List[np.ndarray] = []
        try:
            arr = np.asarray(raw)
            if arr.ndim == 3 and arr.shape[1:] == (64, 64):
                for sub in arr:
                    screens.append(sub.astype(np.int32))
            elif arr.ndim == 2 and arr.shape == (64, 64):
                screens.append(arr.astype(np.int32))
        except Exception as e:
            logger.debug(f"[PERCEPTION] Failed to extract all screens: {e}")
        return screens

    @staticmethod
    def screens_differ(s1: Optional[np.ndarray], s2: Optional[np.ndarray]) -> bool:
        """Check whether two screen frames differ meaningfully in visual content."""
        if s1 is None or s2 is None:
            return True
        if s1.shape != s2.shape:
            return True
        return not np.array_equal(s1, s2)

    def detect_player(
        self,
        screen: np.ndarray,
        last_state: Optional[PlayerState] = None,
        controllable_pos: Optional[Tuple[int, int]] = None,
        stride: int = 5,
        offset_x: int = 4,
        offset_y: int = 0,
    ) -> Optional[PlayerState]:
        """Detect the player avatar on the grid."""
        # 1. First attempt LS20 pattern matching if on default stride
        if stride == 5 and offset_x == 4:
            for c_top in COLORS:
                for c_bot in COLORS:
                    if c_top == c_bot:
                        continue
                    pos = self._search_player_pattern(screen, c_top, c_bot)
                    if pos is not None:
                        x, y = pos
                        col, row = pixel_to_grid(x, y, stride=5, offset_x=4)
                        prev_shape = last_state.shape_idx if last_state else 0
                        prev_color = last_state.color_idx if last_state else 0
                        prev_rot = last_state.rot_idx if last_state else 0
                        player = PlayerState(
                            x=x,
                            y=y,
                            col=col,
                            row=row,
                            top_color=c_top,
                            bottom_color=c_bot,
                            shape_idx=prev_shape,
                            color_idx=prev_color,
                            rot_idx=prev_rot,
                        )
                        self.last_detected_player = player
                        return player

        # 2. Generalization: 4px WA30 avatar search (color 14 avatar block)
        if stride == 4 and offset_x == 0:
            for row in range(16):
                for col in range(16):
                    x = col * 4
                    y = row * 4
                    if x + 4 <= screen.shape[1] and y + 4 <= screen.shape[0]:
                        cell = screen[y : y + 4, x : x + 4]
                        if 14 in cell:
                            player = PlayerState(
                                x=x,
                                y=y,
                                col=col,
                                row=row,
                                top_color=0,
                                bottom_color=14,
                            )
                            self.last_detected_player = player
                            return player

        # 3. Generalization fallback: use dynamically tracked controllable entity
        if controllable_pos is not None:
            col, row = controllable_pos
            x = offset_x + col * stride
            y = offset_y + row * stride
            player = PlayerState(
                x=x,
                y=y,
                col=col,
                row=row,
                top_color=12,
                bottom_color=9,
            )
            self.last_detected_player = player
            return player

        return self.last_detected_player

    def _search_player_pattern(
        self, screen: np.ndarray, c_top: int, c_bot: int
    ) -> Optional[Tuple[int, int]]:
        """Search for a 5x5 block with top 2 rows = c_top, bottom 3 rows = c_bot."""
        for row in range(11):
            for col in range(11):
                x, y = grid_to_pixel(col, row, stride=5, offset_x=4)
                if x + 5 > 64 or y + 5 > 64:
                    continue
                if screen[y, x] != c_top:
                    continue
                top_ok = (
                    np.all(screen[y, x : x + 5] == c_top)
                    and np.all(screen[y + 1, x : x + 5] == c_top)
                )
                bot_ok = (
                    np.all(screen[y + 2, x : x + 5] == c_bot)
                    and np.all(screen[y + 3, x : x + 5] == c_bot)
                    and np.all(screen[y + 4, x : x + 5] == c_bot)
                )
                if top_ok and bot_ok:
                    return (x, y)
        return None

    def parse_hud(self, screen: np.ndarray, levels_completed: int = 0) -> HUDState:
        """Parse status indicators (steps, lives, fog, target) from screen."""
        hud = HUDState(levels_completed=levels_completed)
        if screen is None or screen.shape != (64, 64):
            return hud

        # Check step counter bar at y=61..62, x=13..54
        # Active steps are rendered with bright color (e.g. 10 or 14), depleted with 0 or 4
        active_steps = 0
        for col_idx in range(13, 55):
            val = screen[61, col_idx]
            if val not in (0, 4, -1, -2):
                active_steps += 1
        hud.remaining_steps = active_steps if active_steps > 0 else 42

        # Check lives at y=61..62, x=56, 59, 62
        lives = 0
        for pip_x in [56, 59, 62]:
            if pip_x < 64 and screen[61, pip_x] not in (0, 4, -1, -2):
                lives += 1
        hud.remaining_lives = lives if lives > 0 else 3

        # Check if fog is present (large dark background area)
        hud.has_fog = bool(np.sum(screen[10:40, 10:40] == 0) > 600 and levels_completed >= 6)

        return hud

    def detect_objects(
        self,
        screen: np.ndarray,
        player: Optional[PlayerState] = None,
        stride: int = 5,
        offset_x: int = 4,
        offset_y: int = 0,
        cols: int = 11,
        rows: int = 11,
    ) -> List[GameObject]:
        """Scan discrete grid cells and identify visible objects."""
        objects: List[GameObject] = []
        if screen is None:
            return objects

        player_grid = player.grid_pos if player else None

        # Standard verified LS20 detection path
        if stride == 5 and cols == 11 and offset_x == 4:
            for row in range(11):
                for col in range(11):
                    if player_grid == (col, row):
                        continue

                    x, y = grid_to_pixel(col, row, stride=5, offset_x=4)
                    cell = screen[y : y + 5, x : x + 5]
                    unique_colors = set(np.unique(cell).tolist())

                    obj_type = ObjectType.EMPTY

                    # Wall / Obstacle check
                    if 4 in unique_colors:
                        obj_type = ObjectType.WALL
                    # Goal check (color 5 border or fill)
                    elif 5 in unique_colors:
                        obj_type = ObjectType.GOAL
                    # Refill item check (color 11)
                    elif 11 in unique_colors:
                        obj_type = ObjectType.REFILL
                    # Rotation transformer (contains white pixels 1 and center pattern)
                    elif 1 in unique_colors and 0 in unique_colors and len(unique_colors) <= 3:
                        # Could be rotation transformer or pusher
                        obj_type = ObjectType.TRANSFORMER_ROTATION
                    # Color transformer (contains multiple palette colors 8, 9, 12, 14)
                    elif any(c in unique_colors for c in [8, 9, 12, 14]) and len(unique_colors) > 2:
                        obj_type = ObjectType.TRANSFORMER_COLOR
                    # Shape transformer (contains shape outline)
                    elif len(unique_colors) == 2 and 0 in unique_colors and -2 in unique_colors:
                        obj_type = ObjectType.TRANSFORMER_SHAPE

                    if obj_type != ObjectType.EMPTY:
                        objects.append(
                            GameObject(
                                object_type=obj_type,
                                x=x,
                                y=y,
                                col=col,
                                row=row,
                                width=5,
                                height=5,
                            )
                        )
            return objects

        # Dynamic generalized detection for non-LS20 environments (wa30, g50t, re86)
        vals, counts = np.unique(screen, return_counts=True)
        bg_color = vals[np.argmax(counts)]

        for row in range(rows):
            for col in range(cols):
                if player_grid == (col, row):
                    continue

                x = offset_x + col * stride
                y = offset_y + row * stride
                if x + stride > 64 or y + stride > 64:
                    continue
                cell = screen[y : y + stride, x : x + stride]
                unique_colors = [c for c in np.unique(cell) if c != bg_color and c != -1 and c != 0]
                if not unique_colors:
                    continue

                # Bottom HUD bar (color 7) or out-of-bounds boundary -> WALL
                if row == rows - 1 and (7 in unique_colors or y + stride >= 63):
                    objects.append(
                        GameObject(
                            object_type=ObjectType.WALL,
                            x=x,
                            y=y,
                            col=col,
                            row=row,
                            width=stride,
                            height=stride,
                            color=7,
                        )
                    )
                    continue

                obj_type = ObjectType.UNKNOWN

                # Structural & multi-color evidence
                has_color_2 = (2 in unique_colors)
                has_border_9 = (9 in unique_colors)
                is_pure_flat_2 = (len(unique_colors) == 1 and unique_colors[0] == 2 and np.all(cell == 2))

                # Check spatial neighborhood within screen for border color 9
                neighbor_has_9 = False
                for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                    ny, nx = y + dr * stride, x + dc * stride
                    if 0 <= ny < screen.shape[0] and 0 <= nx < screen.shape[1]:
                        if 9 in screen[ny : ny + stride, nx : nx + stride]:
                            neighbor_has_9 = True
                            break

                if has_color_2 and (has_border_9 or (is_pure_flat_2 and neighbor_has_9)):
                    # Flat bounded receptacle (e.g. jigtxgzhwt, doijajrgdi, ktghqrydvd)
                    obj_type = ObjectType.RECEPTACLE
                elif is_pure_flat_2:
                    # Secondary large flat drop zone
                    obj_type = ObjectType.RECEPTACLE
                elif has_color_2 and not has_border_9 and not is_pure_flat_2:
                    # Textured stippled obstacle block (e.g. pmargquscu containing 2 mixed with texture)
                    obj_type = ObjectType.WALL
                elif len(unique_colors) == 1 and np.all(cell == unique_colors[0]):
                    # Solid uniform foreground block -> WALL
                    obj_type = ObjectType.WALL
                else:
                    # Multi-colored foreground item (e.g. border 4, center 9)
                    obj_type = ObjectType.ITEM

                objects.append(
                    GameObject(
                        object_type=obj_type,
                        x=x,
                        y=y,
                        col=col,
                        row=row,
                        width=stride,
                        height=stride,
                        color=unique_colors[0] if unique_colors else None,
                    )
                )

        return objects

